def word_to_number(word):
    match word:
        case "Zero":
            return 0
        case "One":
            return 1
        case "Two":
            return 2
        case "Three":
            return 3
        case "Four":
            return 4
        case "Five":
            return 5
        case _:
            return word
